### ISSUE TITLE
Question about units

### ISSUE THREAD

**Issue by lukebond** [danielgtaylor/malt.io#85]
Are the gallons used in Malt.io US or Imperial? As a metric user trying to convert I found there are two types of gallons. Who knew...

**Comment by oboyle** [comment]
@lukebond , I believe all of the volume measurements in malt.io are in US gallons.

The formula page at http://www.malt.io/homebrew-formulas is imprecise, as are many of the references in BYO and in forums.

**Comment by lukebond** [comment]
Thanks!
